name: Build and Deploy to SVN
on:
  push:
    tags:
    - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli unzip curl php-mbstring php-xml
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        